=== IkaruBerjuega/VCT/data.dtd
<!ELEMENT vct (team+)>
<!ELEMENT team (logo, teamname, abbreviation, region, members)>
<!ATTLIST team id ID #REQUIRED>
<!ELEMENT logo (#PCDATA)>
<!ELEMENT teamname (#PCDATA)>
<!ELEMENT abbreviation (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT members (member+)>
<!ELEMENT member (name, ign, portrait)>
<!ATTLIST member id ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT ign (#PCDATA)>
<!ELEMENT portrait (#PCDATA)>

=== IkaruBerjuega/VCT/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vct SYSTEM "Data.dtd">
<vct><team id="t2"><logo>https%3A%2F%2Fcdn.sanity.io%2Fimages%2F5gii1snx%2Fproduction%2Fc32c2cb848fd3338ff23a590ec5c0e052b080f27-1000x1000.png</logo><teamname>Fnatic</teamname><abbreviation>FNC</abbreviation><region>VCT+EMEA</region><members><member id="FNC1"><name>Jake Howlett</name><ign>Boaster</ign><portrait>https://cf-img.fnatic.com/cdn-cgi/image/dpr=1,fit=contain,format=auto,height=500,width=1536/https://cdn.sanity.io/images/5gii1snx/production/944ed4d004249326380ea2139693887d32d6a7d1-1000x1000.png</portrait></member><member id="FNC2"><name>Leo Jannesson</name><ign>Leo</ign><portrait>https://cf-img.fnatic.com/cdn-cgi/image/dpr=1,fit=contain,format=auto,height=500,width=1536/https://cdn.sanity.io/images/5gii1snx/production/bd795dbb01efa8ffa6f1b4a7698740ec0c72ae8c-1000x1000.png</portrait></member><member id="FNC3"><name>Emir Ali Beder</name><ign>Alfajer</ign><portrait>https://cf-img.fnatic.com/cdn-cgi/image/dpr=1,fit=contain,format=auto,height=500,width=1536/https://cdn.sanity.io/images/5gii1snx/production/fad544ebd5eac523d3450cf0be6258bea6b2227f-1000x1000.png</portrait></member><member id="FNC4"><name>Timofey Khromov</name><ign>Chronicle</ign><portrait>https://cf-img.fnatic.com/cdn-cgi/image/dpr=1,fit=contain,format=auto,height=500,width=1024/https://cdn.sanity.io/images/5gii1snx/production/c560cfe528a6425bb3b97eade522f97514d1325a-1000x1000.png</portrait></member><member id="FNC5"><name>Moew</name><ign>Derke</ign><portrait>https://cf-img.fnatic.com/cdn-cgi/image/dpr=1,fit=contain,format=auto,height=500,width=1536/https://cdn.sanity.io/images/5gii1snx/production/e131dc635a4b5d7cf7e8e1f1cd4ba560a998424c-1000x1000.png</portrait></member></members></team><team id="t4"><logo>https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2F3%2F33%2FEdward_Gaming_logo.png</logo><teamname>EDward+Gaming</teamname><abbreviation>EDG</abbreviation><region>VCT+China</region><members><member id="EDG1"><name>Guo Haodong</name><ign>Haodong</ign><portrait>https://owcdn.net/img/65c87603071e0.png</portrait></member><member id="EDG2"><name>Wan Shunzhi</name><ign>CHICHOO</ign><portrait>https://owcdn.net/img/65c875f2b3ec5.png</portrait></member><member id="EDG3"><name>Wang Senxu</name><ign>nobody</ign><portrait>https://owcdn.net/img/65c875e1b0670.png</portrait></member><member id="EDG4"><name>Zheng Yongkang</name><ign>ZmjjKK</ign><portrait>https://owcdn.net/img/65c8760abae65.png</portrait></member><member id="EDG5"><name>Zhang Zhao</name><ign>Smoggy</ign><portrait>https://owcdn.net/img/65c875fa773eb.png</portrait></member><member id="EDG6"><name>Tang Shijun</name><ign>Muggle</ign><portrait>https://owcdn.net/img/65c875ea79703.png</portrait></member></members></team><team id="t5"><logo>https%3A%2F%2Fthumbs.dreamstime.com%2Fb%2Ft-logo-white-background-designs-editorial-illustrative-vector-eps-210442161.jpg</logo><teamname>100Thieves</teamname><abbreviation>100T</abbreviation><region>VCT+Americas</region><members><member id="X100T1"><name>Peter Mazuryk</name><ign>Asuna</ign><portrait>https://100thieves.com/cdn/shop/files/val_headshots.jpg?v=1705614390</portrait></member><member id="X100T2"><name>Sean Christian Bezerra</name><ign>bang</ign><portrait>https://100thieves.com/cdn/shop/files/val_headshots2.jpg?v=1705614433</portrait></member><member id="X100T3"><name>Matthew Dylan Panganiban</name><ign>Cryocells</ign><portrait>https://100thieves.com/cdn/shop/files/val_headshots5.jpg?v=1705614598</portrait></member><member id="X100T4"><name>Daniel Vucenovic</name><ign>eeiu</ign><portrait>https://100thieves.com/cdn/shop/files/val_headshots3.jpg?v=1705614467</portrait></member><member id="X100T5"><name>Kelden Elric Pupello</name><ign>Boostio</ign><portrait>https://100thieves.com/cdn/shop/files/val_headshots6.jpg?v=1705614627</portrait></member></members></team><team id="t6"><logo>data%3Aimage%2Fjpeg%3Bbase64%2C%2F9j%2F4AAQSkZJRgABAQAAAQABAAD%2F2wCEAAkGBw0NDQ0NDQ0NDQ0NDQ0ODQ0NDQ8NDQ0NFREWFhURFRYYHSggGB0lHxUTITEiJikrLi4uFx8zODMsNygtLjcBCgoKDQ0NDg0NDy0ZExkrKy0tKysrLSsrKysrKy0rKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrK%2F%2FAABEIAOEA4QMBIgACEQEDEQH%2FxAAcAAEBAAIDAQEAAAAAAAAAAAAAAQIHAwUGCAT%2FxABDEAACAgECAwUEBQcLBQEAAAAAAQIDBAURBhIhBzFBUWETInGRFDJygaEjQlJiY4KxFTM0Q1OUosHC0dJERVRzkhb%2FxAAVAQEBAAAAAAAAAAAAAAAAAAAAAf%2FEABQRAQAAAAAAAAAAAAAAAAAAAAD%2F2gAMAwEAAhEDEQA%2FANJgAAAABCgCMhSAAABAAAKAAAAAFAAAABsCgTYhkQIgAIAAAgKAMgAVQAAAABAwAIAAAAAAAAAVACkKABQBAUAQAAQFIBAUgQAKFUAAAAAAAAhQBiCkAAAAUAAECpACoFAgKAICgCApAIQrIAAYAhQAigAKAAAAAAAAgKAJsCgCF2KgA2KDKuEpvaEZTflBOT%2FACAztqnD68JQ%2B3Fw%2FiYr06gQF2GwEAAEIUgBkKyAQAAAABQAAAAAAAAAAAKkAIdroGhZepZEcXCpldbLq9ukK4eM5y7ox9X%2FE%2BgOBOybB01Qvy1DOzVtLmnHfGoknuvZwfe1%2BlLr06KIGn%2BEuzLVtUUbI0%2FRcaWzWTlb1xlHzhD60%2Fjtt6m1tB7EtKx0pZll%2BfZ03Tk8ejf0jB83zkzZ4A6XT%2BEtJxdnRpuFXJLZTWNW7Nvttb%2FidxCuMekYxil3KKSR12u8Q4OnQ9pm5VWPFreKnL8pP7EF70vuTNdax24YcN44OHdktd1l8ljVv1S96XzSA2vKKfek%2FikzqNR4U0vL3%2Bkadh2trbnlj1%2B0S9JJbr5mk87to1exv2UcTHj4clMpzXxc5NP5I6W%2FtN1yb3eoWJeUK6YL8IgbR13sT0rITlhzvwLOuyjJ5FG%2FrCb5vlJGp%2BL%2BzjVNJUrLKlkYsev0rG3nXFftI%2FWh8WtuveJdoOsv%2FALhkJ%2Bko%2FwCxlDtH1yH1dRufpONdia8mpRaA8YQ%2FXqGU77Z3ShTXKb3lGitU183moLpHfyWy9D8oEMTIxAEKRgCFIAAAGQAAEKQAAAAKZJARRPVcB8D5et3uNP5LGrklkZco7wr%2FAFIr86e3h89jsOzfs7yNasVtnNRp1ctrb9tp2td9dW%2Fe%2FOXcvV9D6S0jS8fBx6sXEqjTRTHlhXDuXm231bfe2%2Brb3YH4%2BF%2BGsPScZY2HXyR6OyyXvXXz%2FTsl4v8ABeCR3AD9O%2Fw38wODOzKcaqd%2BRbCmmtc07LJKEIr1bNJcb9tdljnj6NH2Vfc862H5Wf8A6q39VesuvojYGvcALVpwnqufkX11tuvExVHExIPzcfelKW3TmcvPbbfYzwey7h%2BjrHTq7H4u%2By6%2Ff7pyaX3ID5gzM2y%2ByV19s7rpvedts3OyT9W%2Bpxe0XmvmfXdHCOkV%2FwA3penwfmsOjf58p%2Bn%2BQNP%2FAPBw%2FwC60%2F8AED48U0%2FEvMfXd3Cmk2fzmmafP7WHQ%2F8ASddl9nGgXJqel4sd%2FwCyjKh%2Fc62mgPlbmG59G53YvoVq%2FJwysZ%2BDpyZT2%2B6zmPMap2DPq8PU%2FD3a8qjx9Zwf%2BkDS7MWe21nsr17ETl9EWVBLrPCmr3%2F8dJv7onjcimdU3XbCdVkekq7IShOPxT6oDiZGVkAxBSAAAABCgUpAAB%2BjKwr6OV3U3UqaTg7ap1qSa3TTa69Op%2BbdeYF2LykTS8TveH%2BE9T1OSWFh3Wxf9c4%2Bzx16uyW0fk9wOk7jZfZn2W3an7PMz1OjT%2Bk4Q6xuzV%2Br4wg%2F0u9ru817ngXscxcJwydTlDNyY7SjQk%2FolUvVPra%2FikvTxNpgcWJi1UVwpprhVVVFQrrhFRhCC7kkjlAAAAAA3t1fRebOsz%2BItOxf6RnYlPpZkVxfyb3A7MHjsrtS4fqez1GE3%2BxpvuXzhBo7nhnibD1Wuy3CnOyFc1CTnVOp8zW%2FdJJgdwDzvGPGWJosaJZcb5RyJWRh7CEZtOCTe6bX6R5tdtGjf2ef%2Fd6%2F%2BYGxga%2Fq7YNGl4ZsftY6e%2FykzuNJ4%2B03MnGuh5Mpy7o%2FRLm%2FwTA9QdfrGh4WfD2eZi0ZMfD21cZuPrGXfF%2BqZ2CYA1DxP2G4tilZpeRLFn1ax8hyuob8Ep%2FXj8XzGoOJeE9R0qfJnY06ot7QuXv49n2bF08N9ns%2FQ%2BvTiysaq6udV1cLarE4zrshGdc4%2BTi%2BjQHxWyG9eO%2BxaE1PJ0ZquezlLAsl%2BTm%2F2U5P3H%2BrLp6xNI5uHbRbOm%2BudN1UuWyqyLhOEvJpgcAAAAAAUhQNxdkfaZTRVDStVmo0R93FyresK4%2F2NrfdFeEu5dz6JG4MjhnSr%2Ffs07T7ubZ88sSibkn478vU%2BPT13CHaLqukctdNyvxV%2FwBJk72VJfqPfmh49z269zA%2BlsThjTKHzU6dgVSXdKvEohL5qO52pqvRO3HTLlGObRk4U9velFLJoT%2BMff8A8J6%2FD7QNCvScNVw1v4W3KiXys2YHpQdT%2FwDqNL23%2FlLT9vP6ZR%2FyPw5nHuh0JuzVMPot9oWq2XyjuB6QHi9C7UNI1DOhgY1lrnZGTrtsq9lTZNf1ceZ78zW7XTw%2BB7QDz%2FGHGODo1ULMt2OVvMqaqq3OdriuqT%2Bqu9d7RqrM7csqeTT7HEqx8NX1u52N3ZE6Odc%2B220Yvl38GbI7TOFv5W0%2BVcEvpFD9tjt9N5pNOD%2BK3XyfgfMuTiSrlKEouMotxlGSalGSezTT7mB9f5FNOVROuaVtGTTKEl3xsqsjs%2FuaZ8r8bcFZei5E4W1yliubWNmKO9dtf5qk10jPbvi%2FHu3XU2D2UdpdWNVXpupz5Kq0oYmXL6lcPCq1%2BCXhLu26Pbbd7rrsrurUoShbVZHdSi1OucX69zQHxtp2HflWwoxarL7pvaNdUXOT9encvV9EfUXZnwvLSNNhRc4vKtm78lxe8Y2SSSgn48qUV8d34npqMaupNV111p9XyQjBP47HhOPO0zF0%2BE8fCnDKz2nFcjU6MZ%2FpWNd7X6C6%2BewHiO3fV4ZGfj4dcub6DVN27dyuu5Xyv1UYwf7xrmnH3fcfo2svsnZZKVllk5TsnJ7ynOT3cn97PfcBcFWZtinNctMGnObX4LzYH5OCeBrc%2BabXJVHZzsa6RX%2Bb9DeOhaFjYFSrx61Hp79jS55v1f8AkfrwcOrHqjTTFQhBbJLx9X5s5wIG0k2%2BiXVt9EkdJxbxTh6PjPJy57b7qqmGzuvn%2BjBfxfcvE%2Bc%2BNO0LUdZlKNk3j4jfu4VMmq9v2kujsfx6eSQG99a7TtCwm4TzoXWR33rxYyyWmu9OUfdT%2BLPM3du%2Blpvkws%2Ba85KiG%2F8AjZ8%2FmIG%2F4dvGm%2FnYOevs%2Bwl%2FrR0HGnGPDGvU%2FloZuFmwjtRlyxYSlHyhP2cnzw693h4bGnybgZSXf139Vvs%2FXqYBsAAABQAAAAFAAE5V5IqQKBlXKUZRlGUoyi1KMotxlGSe6kmu5o352cdrdOTCvD1ayNGUkowy5bQoyfLnfdXP8H6dxoOKOaFe4H2emmk0001umuqaNf8AaB2cU6jzZONy05bW8unuXNLpzJeP6y6%2Bj6baX4d4u1fS0o4mXYqV3Y9y9vRt5KMvq%2FutHtsPtxzoJLI07GufjKq%2BzH3%2B5xmB4DW%2BH8rBscMmmdb32Umt65fCS6P4d5%2BTB1DKxf6Nk5GP13aovspi35tRaTNkal2zQyYOFuhUz3Wz9pnOXTy6Up%2Fia%2B1jUoZlinXh4%2BHFb7V4%2FM09%2FNvv%2BQDJ1jOyFy352ZdBrZwtyrpwa9YuWzMcXE32SXwSOXTNPstkoxi5N%2BCRt3g3s4l7t2YnXHo1X%2BfL%2FYDouBeCLMuanNOFMWuabX4LzZuzBw6seuNNMVCEFskvH1fqZ49EKoRrrioQitoxj0SOQAee424uxdFxXkXvnslvHHx4tKy%2BzyXlFdN5eHxaQ404uxNGxnde%2Be2aax8aMkrL5ry8orpvLw9W0j5k4n4gytUyp5eXPmnLpCC6V01p9K4LwS3%2B%2Fq31A4%2BJNfy9Uyp5eZZz2S6RiuldNe%2FSuEfBL5vve7OqZlIwYEMWVkYEZCgCAoAgKQCgpGACIUCgIqAFQKgMon6qFuflRzVy2A3PwRh6HrVMMaytYeo1w2lCEtoZCS%2Fna1Lv83FdV8Op2Wb2N1Sf5LKS%2B3Xt%2FBmj68mUWpRlKMotSjKMnGUZLuaa6p%2BpsnhftkzcZRqz61nVLZK1NV5cV6v6tnh37PzbA7ldik2%2BuZUl6QkztdP7G8ODTvybLPONcIw%2FF7ndaT2paHlJb5Txp9N4ZVcqtv3usP8AEeho4i06xb15%2BHNfq5NT%2FwAwOLROF8DAS%2Bj48IyX9ZL37Pm%2B77juDpsrivSqVvbqOFD0%2Bk1N%2FJM8xq%2Fa%2FouOmqrLsya%2FNx6pRhv9ufKtvhuBsA8Nx72lYekqVNTjlZ%2B2yojL3KX53SXd9ldX6Lqar4r7W9TzlKrH20%2FHlumqJN5Eo%2FrW9Gv3UvizXrfj4ttt%2BbA%2Ffrus5WoZE8rLtlbdN976RhHwhBd0YrwS%2Fi2zrWytmDYBmLKYgCFAGIKyACFAEAAFZDIgGJUNipADJBIuwEKgAMjJGBkgORMyUji3CYHOpEexxqQ3Az3I5GDZGwMmzHcm4ANkBAIyGRAIAABGUgEBQBAABQCpANipDYAXYFCAgMibAQqIVAACAZDcgAu5AAA3BAKQAAQAAQACMhQAAAEBQBlsVIqRlsBjsNjLYuwGARlsTYACoNAYguxABCkAoBdgICgCELsAICkYEIZGIEAIBkAigTYF2GwGOwM9gBybFBQIXYbhAQhk0QACoAYmLMmjFgYlGxUgCRkRFAxYMtibATYbFCAJBxM0i7AcLRNjlaMNgMNhynJymSiBxqJeU5dhsBxco2OblHKBw7A5uUoGCIAAM0AAMWAARQAMWYyIAIVAAZIyAAGIAEKgAM0VlAGEiAAVGTAABAAZRKARAAAf%2F9k%3D</logo><teamname>Team+Secret</teamname><abbreviation>TS</abbreviation><region>VCT+Asia-Pacific</region><members><member id="TS1"><name>Adrian Jiggs Reyes</name><ign>invy </ign><portrait>https://owcdn.net/img/65a8f723b2bdb.png</portrait></member><member id="TS2"><name>Jessie Cuyco</name><ign>JessieVash</ign><portrait>https://owcdn.net/img/65a8f7396035a.png</portrait></member><member id="TS3"><name>Noel De Guia</name><ign>NDG</ign><portrait>https://owcdn.net/img/65a8f74a6111f.png</portrait></member><member id="TS4"><name>Jim Timbreza</name><ign>BORKUM</ign><portrait>https://owcdn.net/img/65a8f72fc308
